openapi: 3.0.0

info:
    title: covidoo-api
    description: user vitals data API

servers:
    - url: http://localhost:3001
      description: local server

paths:
    /users-data:
        get:
            summary: Find All Users Data to display on Map
            responses:
                '200':
                    description: 'OK'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/GetUserDataResponse'
                            example:
                                - _id: 10
                                  username: User 1
                                  userId: auth0|123456
                                  latitude: 31.6
                                  longitude: 32.6
                                  temperature: 40
                                  oxygenLevel: 90
                                  timestamp: 1678131625

                '404':
                    description: 'No Data Found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'
                '500':
                    description: 'Server Error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'

        post:
            summary: Add User Vitals Data Record
            parameters:
                - name: body
                  in: body
                  description: user Data
                  required: true
                  schema:
                      $ref: '#/definitions/CreateUserDataRequest'
            responses:
                '201':
                    description: 'Created'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/CreateUserDataResponse'
                '400':
                    description: 'Bad Request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'
                '500':
                    description: 'Server Error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'

    /users-data/history:
        get:
            summary: Find User Vitals data history
            responses:
                '200':
                    description: 'OK'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/GetUserDataResponse'
                '404':
                    description: 'No Data Found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'
                '500':
                    description: 'Server Error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/definitions/ErrorModel'

definitions:
    UserDataModel:
        type: object
        properties:
            _id:
                type: string
                description: id of the record in mongo
            username:
                type: string
                description: name of the user
            userId:
                type: string
                description: id of the user
            latitude:
                type: number
                description: latitude of user
            longitude:
                type: number
                description: longitude of user
            temperature:
                type: number
                description: temperature of user
            oxygenLevel:
                type: number
                description: oxygen level of user
            timestamp:
                type: number
                description: unix timestamp of the record
    ErrorModel:
        type: object
        properties:
            message:
                type: string
                description: message with the error

    GetUserDataResponse:
        type: object
        properties:
            data:
                type: array
                items:
                    $ref: '#/definitions/UserDataModel'

    CreateUserDataResponse:
        type: object
        properties:
            data:
                $ref: '#/definitions/UserDataModel'

    CreateUserDataRequest:
        type: object
        required:
            - latitude
            - longitude
            - temperature
            - oxygenLevel
        properties:
            latitude:
                type: number
                description: latitude of user
            longitude:
                type: number
                description: longitude of user
            temperature:
                type: number
                description: temperature of user
            oxygenLevel:
                type: number
                description: oxygen level of user

schemes:
    - https
    - http
